### PR TITLE
Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by es128**
@phated

### CODE REVIEW

**Comment by phated** [comment]
@es128 👍  it looks like the failure was a failure with reaching the coveralls API.

Do you want to mention anything about escaping in the readme?

**Comment by phated** [comment]
@es128 hate to keep poking but what do you think here?

Also, what are your thoughts on putting this in the micromatch org?

cc @jonschlinkert @doowb

**Comment by es128** [comment]
I'm fine with moving it to the org. Do you have a suggested patch for the readme?

**Comment by es128** [comment]
@phated just gonna give it about a day to see if @jonschlinkert wants to weigh in. If no dissent, I'll merge, publish, and transfer the repo over to the micromatch org (maybe the last one first).

Feel free to ping me if I forget.

**Comment by jonschlinkert** [comment]
> transfer the repo over to the micromatch org

awesome! 

I'm good with everything mentioned!

**Comment by phated** [comment]
Perfect!  @es128 I appreciate your work here.

**Comment by phated** [comment]
@es128 still able to tackle this today?

**Comment by es128** [comment]
Yup

**Comment by phated** [comment]
master failed just due to the org change.  Coveralls needs to get set up for the micromatch org

**Comment by es128** [comment]
already done

**Pull request merged**
